[pytest]
pythonpath = .
testpaths = tests
markers =
    appium: Appium mobile automation test cases
    selenium: Selenium web automation test cases
    security: Vulnerability and security test cases
    load: Load and performance test cases
addopts = -v -p no:warnings
